baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Douglas-Digital-Temple'
theme = 'PaperMod'

[params]
	# Point PaperMod (and our minimal layout) at a small custom stylesheet
	customCSS = "/css/custom.css"
	# Accent color used across the site (primary/secondary accents)
	accent = "#00bcd4"
